### ISSUE TITLE
Mark vs Disk

### ISSUE THREAD

**Issue by lorvus** [DROPTBASS/maximus-py#21]
We mark _**noughts**_ and _**crosses**_ (**marks**) on a sheet of paper when we play Tic-tac-toe.
We place _**dark**_ and _**light**_ **disks** on a board when we play Reversi.

What we have now is this:
```python
class Mark(Enum):
    Max = 'x'
    Min = 'o'
```
Each game type has it's own class.

I think we should either distinguish marks and discs and make them class specific or rename `Mark` and change the characters of `Max` and `Min` to something more general, otherwise Reversi may SUFFER from inclusivity issues. :cry: :cry: _#HoldYourBreathForReversi_ _#ReversiPiecesMatter_

**Comment by mpolakovic** [comment]
This is a tough call... I say we remove the (not so) general enum, and instead create a properly named one inside each game type class.

One possible drawback of this approach is that it will force frontends/game clients to have to distinguish between the game type being played in code, but it's not the end of the world - likely this has to be done anyway, and there are ways around it if not.
